# Site settings
title: "kedamaian"
email: swsyafiq@protonmail.ch
description: "A dark matte black blog theme for Kedamaian."
baseurl: "/swsyafiq"
#baseurl: ""
url: "https://kedamaian.github.io/swsyafiq"
title_description: "Saat itu tetap indah pada tempat dan zamannya.. bukan kerana kekasaran kandungan waktunya tetapi kerana kehalusan dari kandungan hikmahNya.."
#title_image: "https://www.gravatar.com/avatar/00000000000000000000000000000000?s=500&d=mm"
title_image: "https://static.pexels.com/photos/58557/pexels-photo-58557-medium.jpeg"
google_analytics: "UA-16819629-1"
disqus_account: kedamaian
github_repository: https://github.com/kedamaian/swsyafiq
addthis_id: syabrembo
post_limit: 5

# Social usernames/URLs
twitter_username: tehnoblequran
#github_username:  kedamaian
linkedin_link: https://facebook.com/
stackoverflow_link: https://instagram.com/swsyafiq/
google_plus_link: https://www.reddit.com/r/AskNetsec/

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/tehnoblequran\">tehnoblequran</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/kedamaian/swsyafiq\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]

prose:
  rooturl: '_posts'
  siteurl: 'https://kedamaian.github.io/swsyafiq/'
  media: 'images'
  metadata:
    _posts:
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "true"
      - name: "layout"
        field:
          element: "hidden"
          label: "Layout"
          value: "post"
      - name: "title"
        field:
          label: "Title"
          element: "text"
          value: "An Awesome Headline!"
      - name: "description"
        field:
          element: "text"
          label: "Description"
          placeholder: "Enter Post Description"
      - name: "Headline"
        field:
          element: "text"
          label: "Headline"
          placeholder: "Enter Post Headline"
      - name: "modified"
        field:
          element: "text"
          label: "Has this page been modified?"
          placeholder: "YYYY-MM-DD"
      - name: "categories"
        field:
          element: "multiselect"
          label: "Add categories"
          placeholder: "Choose categories"
          value: personal
          options:
            - name: "Hadis"
              value: Hadis
            - name: "Tazkirah"
              value: Tazkirah
            - name: "Ilmu dan Amalan"
              value: Ilmu dan Amalan
            - name: "Security"
              value: security
            - name: "Privacy & Forensics"
              value: privacy & forensics
            - name: "Howto"
              value: howto
            - name: "Personal"
              value: personal
            - name: "Web-Development"
              value: webdevelopment
          alterable: true
      - name: "tags"
        field:
          element: "text"
          label: "Tags"
          placeholder: "Enter tags, separated by spaces"
      - name: "author"
        field:
          element: "text"
          label: "author"
          value: "tehnoblequran"